"""Tests for the LlamaIndex-backed loader.

The only tests in the suite that would fail if LlamaIndex were deleted. That is
ADR-0003's second exit test stated as a fact about this file: everything above
the adapter runs on fakes, so containment is falsifiable rather than asserted.
"""

from __future__ import annotations

import pytest

from atlas.domain.sources import DOCX_MIMETYPE, PDF_MIMETYPE
from atlas.infrastructure.llamaindex.loaders import LlamaIndexDocumentLoader

pytestmark = pytest.mark.unit


@pytest.fixture
def loader() -> LlamaIndexDocumentLoader:
    # Small chunks so a test can assert on splitting without a wall of text.
    return LlamaIndexDocumentLoader(chunk_size=64, chunk_overlap=16)


def test_short_text_stays_one_segment(loader: LlamaIndexDocumentLoader) -> None:
    segments = loader.split_text("Contact: Deco Addict\nCity: Brussels")

    assert len(segments) == 1
    assert "Deco Addict" in segments[0]


def test_long_text_is_split_in_order(loader: LlamaIndexDocumentLoader) -> None:
    text = " ".join(f"word{index}" for index in range(400))

    segments = loader.split_text(text)

    assert len(segments) > 1
    assert segments[0].startswith("word0")
    assert "word399" in segments[-1]


def test_neighbouring_segments_overlap(loader: LlamaIndexDocumentLoader) -> None:
    """A fact on a boundary has to survive in both pieces, or it is unfindable."""
    text = " ".join(f"word{index}" for index in range(400))

    segments = loader.split_text(text)

    first_words = set(segments[0].split())
    second_words = set(segments[1].split())
    assert first_words & second_words


def test_empty_text_costs_nothing(loader: LlamaIndexDocumentLoader) -> None:
    assert loader.split_text("") == []
    assert loader.split_text("   \n  ") == []


def test_no_segment_is_blank(loader: LlamaIndexDocumentLoader) -> None:
    segments = loader.split_text("First line.\n\n\n\nSecond line.")

    assert all(segment.strip() for segment in segments)


def test_a_text_file_is_read_and_split(loader: LlamaIndexDocumentLoader) -> None:
    content = ("Refunds are accepted within thirty days of delivery. " * 40).encode()

    segments = loader.load_file("policy.txt", content, "text/plain")

    assert len(segments) > 1
    assert "Refunds" in segments[0]


def test_a_text_file_with_invalid_bytes_is_still_read(
    loader: LlamaIndexDocumentLoader,
) -> None:
    """One bad byte must not cost the whole document."""
    segments = loader.load_file("notes.txt", b"caf\xff refund policy", "text/plain")

    assert segments
    assert "refund policy" in segments[0]


def test_a_file_type_with_no_reader_yields_nothing(
    loader: LlamaIndexDocumentLoader,
) -> None:
    assert loader.load_file("archive.zip", b"PK\x03\x04", "application/zip") == []


def test_an_unreadable_pdf_yields_nothing_rather_than_failing(
    loader: LlamaIndexDocumentLoader,
) -> None:
    """One corrupt attachment must not be able to block a corpus."""
    assert loader.load_file("broken.pdf", b"not really a pdf", PDF_MIMETYPE) == []


def test_an_unreadable_docx_yields_nothing_rather_than_failing(
    loader: LlamaIndexDocumentLoader,
) -> None:
    assert loader.load_file("broken.docx", b"not really a docx", DOCX_MIMETYPE) == []


def test_an_empty_file_yields_nothing(loader: LlamaIndexDocumentLoader) -> None:
    assert loader.load_file("empty.txt", b"", "text/plain") == []


def test_a_real_pdf_is_extracted(loader: LlamaIndexDocumentLoader) -> None:
    """Proves the reader is wired up, not merely that failures are caught."""
    pdf = _minimal_pdf("Refund policy applies for thirty days.")

    segments = loader.load_file("policy.pdf", pdf, PDF_MIMETYPE)

    assert segments
    assert "Refund policy" in " ".join(segments)


def _minimal_pdf(message: str) -> bytes:
    """Build the smallest PDF that contains a line of text.

    Handwritten rather than generated by a library: adding a PDF *writer* as a
    test dependency to check a PDF *reader* is a lot of moving parts for one
    assertion.
    """
    stream = f"BT /F1 24 Tf 72 720 Td ({message}) Tj ET".encode()
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>"
        ),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_at}\n".encode()
    out += b"%%EOF\n"
    return bytes(out)
